### ISSUE TITLE
Maps zoom buttons appear as sold white boxes

### ISSUE THREAD

**Issue by kaveh096** [googleinterns/univiz#127]
[Screenshot](http://screen/3HpERppAaZEwx8g)

URL to reproduce: https://uni-viz.appspot.com/dashboard.html?id=123961

Assigning to @biancamacias 
CC @ihsan314 in case this is related to the new html theme.

**Comment by ihsan314** [comment]
As seen in this [screenshot](https://screenshot.googleplex.com/59EJ4GtkD4Jmige) if I have the browser window set to half the Dell monitor's screen width and further open the console, the buttons reappear. I'm checking to see if any specific CSS styling is impacting with the visibility of the icons on the zoom boxes.

**Comment by ihsan314** [comment]
I think I caught the issue. Here's how the button size is represented when the screen is iPhone sized:
![image](https://user-images.githubusercontent.com/43079005/91770130-7abbbd80-eb95-11ea-8e54-5f4b47c4aa46.png)
And here's how it is represented when the screen is normally size:
![image](https://user-images.githubusercontent.com/43079005/91770234-afc81000-eb95-11ea-984d-f429be0eec37.png)
The icon widened with the rest of the screen instead of staying at it's assigned width of 40px. The icons are probably centered, and the leftmost 40px are not in the center. That explains why it disappeared. It does sound like a CSS problem at this point.
