### ISSUE TITLE
Reorganize java file structure

### ISSUE THREAD

**Issue by mmurray22** [googleinterns/univiz#85]
Currently we have a series of packages and many files are filed away correctly in these packages. However, this organization could be much better than it currently is, and that's what this issue hopes to address. Specifically, we would like to have the following structure:

package com.google.univiz:
- Stuff

package com.google.univiz.api:
- SearchResourceImpl.java
- MapResourceImpl.java
- VisResourceImpl.java
-SuggestionDataApiImpl.java 

package com.google.univiz.api.resource:
- SearchResource.java
- MapResource.java
- VisResource.java
- SuggestionDataApi.java
- CollegeId.java
- MapData.java
- VisData.java
- SuggestionData.java

package com.google.univiz.scorecard:
- ScorecardData.java
- CarnegieSizeDegree.java
- CollegeData.java
- CollegeDataApi.java
- ScorecardConverter.java

Also, as this structure is changed for the regular files, it should similarly be reflected in the test & resources files.

Please amend/add anything to this issue if something seems off or the structure changes.

**Comment by ccondit** [comment]
minor nit here on the locations just to reflect that we wanted to introduce a `representations` package to hold the univiz value classes. How about something like:

* package com.google.univiz.api:
  * SuggestionDataApiImpl.java
  * SuggestionDataApi.java
  * CollegeDataApi.java
* package com.google.univiz.api.resource:
  * SearchResource.java
  * MapResource.java
  * VisResource.java
  * SearchResourceImpl.java
  * MapResourceImpl.java
  * VisResourceImpl.java
* package com.google.univiz.api.representation:
  * CollegeId.java
  * MapData.java
  * VisData.java
  * CollegeData.java
  * SuggestionData.java
  * CarnegieSizeDegree.java
* package com.google.univiz.scorecard:
  * ScorecardData.java
  * ScorecardConverter.java

Also note that since `CarnegieSizeDegree` is used by `CollegeData` - let's keep it out of the scorecard package.

WDYT?

**Comment by biancamacias** [comment]
> minor nit here on the locations just to reflect that we wanted to introduce a `representations` package to hold the univiz value classes. How about something like:
> 
> * package com.google.univiz.api:
>   
>   * SuggestionDataApiImpl.java
>   * SuggestionDataApi.java
>   * CollegeDataApi.java
> * package com.google.univiz.api.resource:
>   
>   * SearchResource.java
>   * MapResource.java
>   * VisResource.java
>   * SearchResourceImpl.java
>   * MapResourceImpl.java
>   * VisResourceImpl.java
> * package com.google.univiz.api.representation:
>   
>   * CollegeId.java
>   * MapData.java
>   * VisData.java
>   * CollegeData.java
>   * SuggestionData.java
>   * CarnegieSizeDegree.java
> * package com.google.univiz.scorecard:
>   
>   * ScorecardData.java
>   * ScorecardConverter.java
> 
> Also note that since `CarnegieSizeDegree` is used by `CollegeData` - let's keep it out of the scorecard package.
> 
> WDYT?

i like this organization. i will implement this as soon as the resource PRs get merged.

**Comment by mmurray22** [comment]
@ccondit Sounds good!
